CREATE TABLE IF NOT EXISTS votes (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  framework VARCHAR(64) NOT NULL,
  score SMALLINT NOT NULL,
  comment VARCHAR(256),
  dt_created DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
